### PR TITLE
Fix result printing bugs

### LINKED ISSUE #456: [TODO, not urgent] Fix order of arguments in the printing of counterexamples
The counterexamples are printed with the inputs, but they are out of order at this time.

### LINKED ISSUE #457: [TODO, not urgent] Fix counterexample printing when ignoring the assertions
When setting `assertion_semantics` to ignore, the solver is correctly ignoring the assertions when constructing the formulas, but the printer will still check if there are any assertion violation, and print them.

### PR DESCRIPTION
**Pull request by lsrcz**
Fix print order for the function input in proof results (fixes #456). Always print the value no matter assertion happens or not (fixes #457).

### CODE REVIEW

File: xlsynth-g8r/src/equiv/prove_equiv.rs [hunk 1]
```diff
@@ -904,8 +923,10 @@ impl std::fmt::Display for FnOutput {
 pub enum EquivResult {
     Proved,
     Disproved {
-        inputs: Vec<IrValue>,
-        outputs: (FnOutput, FnOutput),
+        lhs_inputs: Vec<(String, IrValue)>,
```
Comment (cdleary) [inline xlsynth-g8r/src/equiv/prove_equiv.rs:926]: Should we make a FnInput struct analogous to the FnOutput struct you have here?

**Review by cdleary — APPROVED** [review]
